package com.acip.usage;

import com.acip.capture.UsageCaptureConfidence;
import com.acip.capture.UsageCaptureMethod;
import com.acip.capture.UsageCaptureSource;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public record UsageEvent(
        UUID id,
        String provider,
        String model,
        String storyKey,
        String epicKey,
        String teamKey,
        String userKey,
        int promptTokens,
        int completionTokens,
        int totalTokens,
        BigDecimal estimatedCostUsd,
        long latencyMs,
        OffsetDateTime requestTimestamp,
        String environment,
        String workType,
        String requestStatus,
        AttributionStatus attributionStatus,
        String requestHash,
        UsageCaptureSource captureSource,
        String captureProvider,
        UsageCaptureMethod captureMethod,
        UsageCaptureConfidence captureConfidence,
        AttributionSource attributionSource,
        AttributionConfidence attributionConfidence,
        String inferredStoryKey,
        String inferenceReason,
        String repository,
        String branch,
        String commitHash,
        String initiativeKey,
        String initiativeName,
        boolean attributionCorrected,
        OffsetDateTime correctedTimestamp,
        String correctedBy
) {
    public UsageEvent(
            UUID id,
            String provider,
            String model,
            String storyKey,
            String epicKey,
            String teamKey,
            String userKey,
            int promptTokens,
            int completionTokens,
            int totalTokens,
            BigDecimal estimatedCostUsd,
            long latencyMs,
            OffsetDateTime requestTimestamp,
            String environment,
            String workType,
            String requestStatus,
            AttributionStatus attributionStatus,
            String requestHash
    ) {
        this(
                id,
                provider,
                model,
                storyKey,
                epicKey,
                teamKey,
                userKey,
                promptTokens,
                completionTokens,
                totalTokens,
                estimatedCostUsd,
                latencyMs,
                requestTimestamp,
                environment,
                workType,
                requestStatus,
                attributionStatus,
                requestHash,
                UsageCaptureSource.PROXY,
                "OPENAI_COMPATIBLE_PROXY",
                UsageCaptureMethod.REAL_TIME_PROXY,
                UsageCaptureConfidence.HIGH,
                storyKey == null || storyKey.isBlank() ? AttributionSource.MISSING : AttributionSource.EXPLICIT,
                storyKey == null || storyKey.isBlank() ? AttributionConfidence.LOW : AttributionConfidence.HIGH,
                null,
                storyKey == null || storyKey.isBlank() ? "No explicit story key was provided." : "Story key was provided explicitly.",
                null,
                null,
                null,
                null,
                null,
                false,
                null,
                null
        );
    }

    public UsageEvent(
            UUID id,
            String provider,
            String model,
            String storyKey,
            String epicKey,
            String teamKey,
            String userKey,
            int promptTokens,
            int completionTokens,
            int totalTokens,
            BigDecimal estimatedCostUsd,
            long latencyMs,
            OffsetDateTime requestTimestamp,
            String environment,
            String workType,
            String requestStatus,
            AttributionStatus attributionStatus,
            String requestHash,
            String repository,
            String branch,
            String commitHash,
            String initiativeKey,
            String initiativeName,
            boolean attributionCorrected,
            OffsetDateTime correctedTimestamp,
            String correctedBy
    ) {
        this(
                id,
                provider,
                model,
                storyKey,
                epicKey,
                teamKey,
                userKey,
                promptTokens,
                completionTokens,
                totalTokens,
                estimatedCostUsd,
                latencyMs,
                requestTimestamp,
                environment,
                workType,
                requestStatus,
                attributionStatus,
                requestHash,
                UsageCaptureSource.PROXY,
                "OPENAI_COMPATIBLE_PROXY",
                UsageCaptureMethod.REAL_TIME_PROXY,
                UsageCaptureConfidence.HIGH,
                attributionCorrected ? AttributionSource.MANUAL : storyKey == null || storyKey.isBlank() ? AttributionSource.MISSING : AttributionSource.EXPLICIT,
                attributionCorrected ? AttributionConfidence.HIGH : storyKey == null || storyKey.isBlank() ? AttributionConfidence.LOW : AttributionConfidence.HIGH,
                null,
                attributionCorrected ? "Manual correction was applied." : storyKey == null || storyKey.isBlank() ? "No explicit story key was provided." : "Story key was provided explicitly.",
                repository,
                branch,
                commitHash,
                initiativeKey,
                initiativeName,
                attributionCorrected,
                correctedTimestamp,
                correctedBy
        );
    }
}
